// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmrrsrdgmbahicdlrerk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtcnJzcmRnbWJhaGljZGxyZXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2MjA0NzYsImV4cCI6MjA1MjE5NjQ3Nn0.lViOjWEoIdJX_leIAFjEdJUN208rMbLlU2QafV_TPWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);